linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - revive
    - misspell
    - gocritic
    - unconvert
    - prealloc
    - nilerr
    - makezero
    - copyloopvar

linters-settings:
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: error-return
      - name: error-strings
      - name: if-return
      - name: increment-decrement
      - name: indent-error-flow
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: unnecessary-stmt
      - name: unreachable-code

  gocritic:
    disabled-checks:
      - hugeParam
      - octalLiteral
    enabled-tags:
      - diagnostic
      - style
      - performance

issues:
  exclude-dirs:
    - testdata

run:
  timeout: 5m
